version: '2'
services:
    microapp-app:
        image: microapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://microapp-postgresql:5432/testdb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    microapp-postgresql:
        extends:
            file: postgresql.yml
            service: microapp-postgresql
